# Generated by Django 5.2.3 on 2025-07-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cost_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='selling_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_revenue',
            field=models.FloatField(),
        ),
        migrations.AlterModelTable(
            name='sale',
            table='sales_fact',
        ),
    ]
